/**
 * CarPool API
 * API documentation for CarPool application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RideRequestResponse from './RideRequestResponse';

/**
 * The PageResponseRideRequestResponse model module.
 * @module model/PageResponseRideRequestResponse
 * @version 1.0
 */
class PageResponseRideRequestResponse {
    /**
     * Constructs a new <code>PageResponseRideRequestResponse</code>.
     * @alias module:model/PageResponseRideRequestResponse
     */
    constructor() { 
        
        PageResponseRideRequestResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageResponseRideRequestResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageResponseRideRequestResponse} obj Optional instance to populate.
     * @return {module:model/PageResponseRideRequestResponse} The populated <code>PageResponseRideRequestResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageResponseRideRequestResponse();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], [RideRequestResponse]);
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('first')) {
                obj['first'] = ApiClient.convertToType(data['first'], 'Boolean');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PageResponseRideRequestResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PageResponseRideRequestResponse</code>.
     */
    static validateJSON(data) {
        if (data['content']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['content'])) {
                throw new Error("Expected the field `content` to be an array in the JSON data but got " + data['content']);
            }
            // validate the optional field `content` (array)
            for (const item of data['content']) {
                RideRequestResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/RideRequestResponse>} content
 */
PageResponseRideRequestResponse.prototype['content'] = undefined;

/**
 * @member {Number} number
 */
PageResponseRideRequestResponse.prototype['number'] = undefined;

/**
 * @member {Number} size
 */
PageResponseRideRequestResponse.prototype['size'] = undefined;

/**
 * @member {Number} totalElements
 */
PageResponseRideRequestResponse.prototype['totalElements'] = undefined;

/**
 * @member {Number} totalPages
 */
PageResponseRideRequestResponse.prototype['totalPages'] = undefined;

/**
 * @member {Boolean} first
 */
PageResponseRideRequestResponse.prototype['first'] = undefined;

/**
 * @member {Boolean} last
 */
PageResponseRideRequestResponse.prototype['last'] = undefined;






export default PageResponseRideRequestResponse;

