/**
 * CarPool API
 * API documentation for CarPool application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarPoolApi);
  }
}(this, function(expect, CarPoolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CarPoolApi.RideRequestResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RideRequestResponse', function() {
    it('should create an instance of RideRequestResponse', function() {
      // uncomment below and update the code to test RideRequestResponse
      //var instance = new CarPoolApi.RideRequestResponse();
      //expect(instance).to.be.a(CarPoolApi.RideRequestResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CarPoolApi.RideRequestResponse();
      //expect(instance).to.be();
    });

    it('should have the property requestStatus (base name: "requestStatus")', function() {
      // uncomment below and update the code to test the property requestStatus
      //var instance = new CarPoolApi.RideRequestResponse();
      //expect(instance).to.be();
    });

    it('should have the property rideOfferId (base name: "rideOfferId")', function() {
      // uncomment below and update the code to test the property rideOfferId
      //var instance = new CarPoolApi.RideRequestResponse();
      //expect(instance).to.be();
    });

    it('should have the property requesterEmail (base name: "requesterEmail")', function() {
      // uncomment below and update the code to test the property requesterEmail
      //var instance = new CarPoolApi.RideRequestResponse();
      //expect(instance).to.be();
    });

    it('should have the property requestDate (base name: "requestDate")', function() {
      // uncomment below and update the code to test the property requestDate
      //var instance = new CarPoolApi.RideRequestResponse();
      //expect(instance).to.be();
    });

  });

}));
