/**
 * CarPool API
 * API documentation for CarPool application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarPoolApi);
  }
}(this, function(expect, CarPoolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CarPoolApi.RideOfferApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RideOfferApi', function() {
    describe('createRideOffer', function() {
      it('should call createRideOffer successfully', function(done) {
        //uncomment below and update the code to test createRideOffer
        //instance.createRideOffer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRideOffer', function() {
      it('should call deleteRideOffer successfully', function(done) {
        //uncomment below and update the code to test deleteRideOffer
        //instance.deleteRideOffer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editRideOfferDetails', function() {
      it('should call editRideOfferDetails successfully', function(done) {
        //uncomment below and update the code to test editRideOfferDetails
        //instance.editRideOfferDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findAllRideOffers', function() {
      it('should call findAllRideOffers successfully', function(done) {
        //uncomment below and update the code to test findAllRideOffers
        //instance.findAllRideOffers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findAllRideOffersPaginated', function() {
      it('should call findAllRideOffersPaginated successfully', function(done) {
        //uncomment below and update the code to test findAllRideOffersPaginated
        //instance.findAllRideOffersPaginated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('viewRideOfferDetails', function() {
      it('should call viewRideOfferDetails successfully', function(done) {
        //uncomment below and update the code to test viewRideOfferDetails
        //instance.viewRideOfferDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
