/**
 * CarPool API
 * API documentation for CarPool application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarPoolApi);
  }
}(this, function(expect, CarPoolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CarPoolApi.RideRequestApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RideRequestApi', function() {
    describe('answerRideOffer', function() {
      it('should call answerRideOffer successfully', function(done) {
        //uncomment below and update the code to test answerRideOffer
        //instance.answerRideOffer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createRideRequest', function() {
      it('should call createRideRequest successfully', function(done) {
        //uncomment below and update the code to test createRideRequest
        //instance.createRideRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRideOffers', function() {
      it('should call getRideOffers successfully', function(done) {
        //uncomment below and update the code to test getRideOffers
        //instance.getRideOffers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRideRequestsForRideOfferPaginated', function() {
      it('should call getRideRequestsForRideOfferPaginated successfully', function(done) {
        //uncomment below and update the code to test getRideRequestsForRideOfferPaginated
        //instance.getRideRequestsForRideOfferPaginated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('viewUsersRideRequests', function() {
      it('should call viewUsersRideRequests successfully', function(done) {
        //uncomment below and update the code to test viewUsersRideRequests
        //instance.viewUsersRideRequests(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('viewUsersRideRequestsPaginated', function() {
      it('should call viewUsersRideRequestsPaginated successfully', function(done) {
        //uncomment below and update the code to test viewUsersRideRequestsPaginated
        //instance.viewUsersRideRequestsPaginated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
