/**
 * CarPool API
 * API documentation for CarPool application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AnswerRideRequestRequest from './model/AnswerRideRequestRequest';
import AuthenticationRequest from './model/AuthenticationRequest';
import EditRideOfferRequest from './model/EditRideOfferRequest';
import PageResponseRideOfferResponse from './model/PageResponseRideOfferResponse';
import PageResponseRideRequestResponse from './model/PageResponseRideRequestResponse';
import PageResponseUserResponse from './model/PageResponseUserResponse';
import RegisterRequest from './model/RegisterRequest';
import RideOfferRequest from './model/RideOfferRequest';
import RideOfferResponse from './model/RideOfferResponse';
import RideRequestRequest from './model/RideRequestRequest';
import RideRequestResponse from './model/RideRequestResponse';
import UserResponse from './model/UserResponse';
import AuthenticationRegistrationApi from './api/AuthenticationRegistrationApi';
import RideOfferApi from './api/RideOfferApi';
import RideRequestApi from './api/RideRequestApi';
import UserApi from './api/UserApi';


/**
* API documentation for CarPool application.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CarPoolApi = require('index'); // See note below*.
* var xxxSvc = new CarPoolApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CarPoolApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CarPoolApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CarPoolApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AnswerRideRequestRequest model constructor.
     * @property {module:model/AnswerRideRequestRequest}
     */
    AnswerRideRequestRequest,

    /**
     * The AuthenticationRequest model constructor.
     * @property {module:model/AuthenticationRequest}
     */
    AuthenticationRequest,

    /**
     * The EditRideOfferRequest model constructor.
     * @property {module:model/EditRideOfferRequest}
     */
    EditRideOfferRequest,

    /**
     * The PageResponseRideOfferResponse model constructor.
     * @property {module:model/PageResponseRideOfferResponse}
     */
    PageResponseRideOfferResponse,

    /**
     * The PageResponseRideRequestResponse model constructor.
     * @property {module:model/PageResponseRideRequestResponse}
     */
    PageResponseRideRequestResponse,

    /**
     * The PageResponseUserResponse model constructor.
     * @property {module:model/PageResponseUserResponse}
     */
    PageResponseUserResponse,

    /**
     * The RegisterRequest model constructor.
     * @property {module:model/RegisterRequest}
     */
    RegisterRequest,

    /**
     * The RideOfferRequest model constructor.
     * @property {module:model/RideOfferRequest}
     */
    RideOfferRequest,

    /**
     * The RideOfferResponse model constructor.
     * @property {module:model/RideOfferResponse}
     */
    RideOfferResponse,

    /**
     * The RideRequestRequest model constructor.
     * @property {module:model/RideRequestRequest}
     */
    RideRequestRequest,

    /**
     * The RideRequestResponse model constructor.
     * @property {module:model/RideRequestResponse}
     */
    RideRequestResponse,

    /**
     * The UserResponse model constructor.
     * @property {module:model/UserResponse}
     */
    UserResponse,

    /**
    * The AuthenticationRegistrationApi service constructor.
    * @property {module:api/AuthenticationRegistrationApi}
    */
    AuthenticationRegistrationApi,

    /**
    * The RideOfferApi service constructor.
    * @property {module:api/RideOfferApi}
    */
    RideOfferApi,

    /**
    * The RideRequestApi service constructor.
    * @property {module:api/RideRequestApi}
    */
    RideRequestApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
